name: matrix-guardian
services:
  guardian:
    container_name: guardian
    image: "ghcr.io/cyb3rko/matrix-guardian:main"
    volumes:
      - guardian-data:/data
    environment:
      # REQUIRED
      GUARDIAN_HOMESERVER: "https://matrix.org"
      GUARDIAN_USERNAME: "yourCoolUsername"
      GUARDIAN_PASSWORD: "yourVerySecurePassword"
      GUARDIAN_MANAGEMENT_ROOM_ID: "!ABCdefGHIjklMNOpqr:matrix.org"
      # Optional (defaults filled in)
      GUARDIAN_MANAGEMENT_ROOM_REPORTS: true
      GUARDIAN_TEST_MODE: false
      GUARDIAN_HIDDEN_MODE: false
      GUARDIAN_VIRUS_TOTAL_KEY: ""
      GUARDIAN_URL_FILTER: true
      GUARDIAN_URL_CHECK_VIRUS_TOTAL: false
      GUARDIAN_URL_CHECK_FISHFISH: false
      GUARDIAN_MIME_FILTER: true
      GUARDIAN_VIRUS_CHECK_VIRUS_TOTAL: false

volumes:
  guardian-data:
